version: "3"
services:
  nodejs_app:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb+srv://hamzah:Fcbarcelona1!@cluster0.em5f8.mongodb.net/shop?retryWrites=true&w=majority
      PORT: 5000

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  react_client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"

volumes:
  mongodb_data:
