/* eslint-disable */
export enum ActionType {
  ADD_TO_CART = "ADD_TO_CART",
  LOGIN_REQUEST = "LOGIN_REQUEST",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAIL = "LOGIN_FAIL",
  GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAIL = "GET_ALL_PRODUCTS_FAIL",
  GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST",
  GET_ALL_CATEGORIES_REQUEST = "GET_ALL_CATEGORIES_REQUEST",
  GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_FAIL = "GET_ALL_CATEGORIES_FAIL",
  REGISTER_REQUEST = "REGISTER_REQUEST",
  REGISTER_SUCCESS = "REGISTER_SUCCESS",
  REGISTER_FAIL = "REGISTER_FAIL",
}
